--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: sonarqube-deployment
  name: sonarqube
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube  
    spec: 
      containers: 
        - 
          env: 
            - 
              name: SONARQUBE_JDBC_USERNAME
              value: sonarqube
            - 
              name: SONARQUBE_JDBC_URL
              value: "jdbc:postgresql://postgresdb:5432/sonardb"
            - 
              name: SONARQUBE_JDBC_PASSWORD
              value: yourpassword
          image: "sonarqube:latest"
          name: sonarqube-pod
          ports: 
            - 
              containerPort: 9000
              protocol: TCP
          resources: 
            limits: 
              cpu: 2000m
              memory: 2048Mi
            requests: 
              cpu: 500m
              memory: 1024Mi
          volumeMounts: 
            - 
              mountPath: /opt/sonarqube/data/
              name: sonarqube-data
            - 
              mountPath: /opt/sonarqube/extensions/
              name: sonarqube-extensions
      volumes: 
        - 
          name: sonarqube-data
          persistentVolumeClaim: 
            claimName: sonarqube-datapv-claim
        - 
          name: sonarqube-extensions
          persistentVolumeClaim: 
            claimName: sonarqube-extensionspv-claim
